namespace PgPassthrough.SqlParser.Lexer;

/// <summary>
/// Static lookup table: uppercase keyword text → <see cref="TokenKind"/>.
/// The lexer upper-cases the text it scans and checks here.
/// Any word not in this table is emitted as <see cref="TokenKind.Identifier"/>.
/// </summary>
internal static class Keywords
{
    public static readonly Dictionary<string, TokenKind> Map =
        new(StringComparer.OrdinalIgnoreCase)
    {
        // DML
        ["SELECT"]      = TokenKind.KwSelect,
        ["FROM"]        = TokenKind.KwFrom,
        ["WHERE"]       = TokenKind.KwWhere,
        ["AND"]         = TokenKind.KwAnd,
        ["OR"]          = TokenKind.KwOr,
        ["NOT"]         = TokenKind.KwNot,
        ["IN"]          = TokenKind.KwIn,
        ["LIKE"]        = TokenKind.KwLike,
        ["BETWEEN"]     = TokenKind.KwBetween,
        ["IS"]          = TokenKind.KwIs,
        ["NULL"]        = TokenKind.KwNull,
        ["AS"]          = TokenKind.KwAs,
        ["ON"]          = TokenKind.KwOn,
        ["JOIN"]        = TokenKind.KwJoin,
        ["INNER"]       = TokenKind.KwInner,
        ["LEFT"]        = TokenKind.KwLeft,
        ["RIGHT"]       = TokenKind.KwRight,
        ["FULL"]        = TokenKind.KwFull,
        ["OUTER"]       = TokenKind.KwOuter,
        ["CROSS"]       = TokenKind.KwCross,
        ["APPLY"]       = TokenKind.KwApply,
        ["UNION"]       = TokenKind.KwUnion,
        ["ALL"]         = TokenKind.KwAll,
        ["DISTINCT"]    = TokenKind.KwDistinct,
        ["TOP"]         = TokenKind.KwTop,
        ["PERCENT"]     = TokenKind.KwPercent,
        ["WITH"]        = TokenKind.KwWith,
        ["TIES"]        = TokenKind.KwWithTies,
        ["ORDER"]       = TokenKind.KwOrderBy,
        ["BY"]          = TokenKind.KwBy,
        ["GROUP"]       = TokenKind.KwGroupBy,
        ["HAVING"]      = TokenKind.KwHaving,
        ["ASC"]         = TokenKind.KwAsc,
        ["DESC"]        = TokenKind.KwDesc,
        ["INSERT"]      = TokenKind.KwInsert,
        ["INTO"]        = TokenKind.KwInto,
        ["VALUES"]      = TokenKind.KwValues,
        ["UPDATE"]      = TokenKind.KwUpdate,
        ["SET"]         = TokenKind.KwSet,
        ["DELETE"]      = TokenKind.KwDelete,
        ["TRUNCATE"]    = TokenKind.KwTruncate,
        ["TABLE"]       = TokenKind.KwTable,
        ["CREATE"]      = TokenKind.KwCreate,
        ["ALTER"]       = TokenKind.KwAlter,
        ["DROP"]        = TokenKind.KwDrop,
        ["INDEX"]       = TokenKind.KwIndex,
        ["VIEW"]        = TokenKind.KwView,
        ["PROCEDURE"]   = TokenKind.KwProcedure,
        ["PROC"]        = TokenKind.KwProc,
        ["FUNCTION"]    = TokenKind.KwFunction,
        ["TRIGGER"]     = TokenKind.KwTrigger,
        ["DATABASE"]    = TokenKind.KwDatabase,
        ["SCHEMA"]      = TokenKind.KwSchema,

        // Table hints
        ["NOLOCK"]          = TokenKind.KwNolock,
        ["ROWLOCK"]         = TokenKind.KwRowlock,
        ["UPDLOCK"]         = TokenKind.KwUpdlock,
        ["XLOCK"]           = TokenKind.KwXlock,
        ["READPAST"]        = TokenKind.KwReadpast,
        ["FORCESEEK"]       = TokenKind.KwForceseek,
        ["FORCESCAN"]       = TokenKind.KwForcescan,
        ["NOEXPAND"]        = TokenKind.KwNoexpand,
        ["READCOMMITTED"]   = TokenKind.KwReadcommitted,
        ["READUNCOMMITTED"] = TokenKind.KwReaduncommitted,
        ["REPEATABLEREAD"]  = TokenKind.KwRepeatableread,
        ["SERIALIZABLE"]    = TokenKind.KwSerializable,
        ["SNAPSHOT"]        = TokenKind.KwSnapshot,
        ["PAGLOCK"]         = TokenKind.KwPaglock,
        ["TABLOCK"]         = TokenKind.KwTablock,
        ["HOLDLOCK"]        = TokenKind.KwHoldlock,

        // Transactions / flow
        ["BEGIN"]       = TokenKind.KwBegin,
        ["END"]         = TokenKind.KwEnd,
        ["COMMIT"]      = TokenKind.KwCommit,
        ["ROLLBACK"]    = TokenKind.KwRollback,
        ["TRANSACTION"] = TokenKind.KwTransaction,
        ["TRAN"]        = TokenKind.KwTran,
        ["SAVE"]        = TokenKind.KwSave,
        ["SAVEPOINT"]   = TokenKind.KwSavepoint,
        ["TRY"]         = TokenKind.KwTry,
        ["CATCH"]       = TokenKind.KwCatch,
        ["THROW"]       = TokenKind.KwThrow,
        ["RAISERROR"]   = TokenKind.KwRaiserror,
        ["IF"]          = TokenKind.KwIf,
        ["ELSE"]        = TokenKind.KwElse,
        ["WHILE"]       = TokenKind.KwWhile,
        ["BREAK"]       = TokenKind.KwBreak,
        ["CONTINUE"]    = TokenKind.KwContinue,
        ["RETURN"]      = TokenKind.KwReturn,
        ["GOTO"]        = TokenKind.KwGoto,
        ["WAITFOR"]     = TokenKind.KwWaitfor,
        ["DELAY"]       = TokenKind.KwDelay,
        ["PRINT"]       = TokenKind.KwPrint,

        // Expressions
        ["CAST"]        = TokenKind.KwCast,
        ["CONVERT"]     = TokenKind.KwConvert,
        ["TRY_CAST"]    = TokenKind.KwTry_Cast,
        ["TRY_CONVERT"] = TokenKind.KwTry_Convert,
        ["CASE"]        = TokenKind.KwCase,
        ["WHEN"]        = TokenKind.KwWhen,
        ["THEN"]        = TokenKind.KwThen,
        ["COALESCE"]    = TokenKind.KwCoalesce,
        ["NULLIF"]      = TokenKind.KwNullif,
        ["ISNULL"]      = TokenKind.KwIsnull,
        ["EXISTS"]      = TokenKind.KwExists,
        ["ANY"]         = TokenKind.KwAny,
        ["SOME"]        = TokenKind.KwSome,

        // Data types
        ["INT"]              = TokenKind.KwInt,
        ["INTEGER"]          = TokenKind.KwInt,
        ["BIGINT"]           = TokenKind.KwBigint,
        ["SMALLINT"]         = TokenKind.KwSmallint,
        ["TINYINT"]          = TokenKind.KwTinyint,
        ["BIT"]              = TokenKind.KwBit,
        ["FLOAT"]            = TokenKind.KwFloat,
        ["REAL"]             = TokenKind.KwReal,
        ["DECIMAL"]          = TokenKind.KwDecimal,
        ["NUMERIC"]          = TokenKind.KwNumeric,
        ["MONEY"]            = TokenKind.KwMoney,
        ["SMALLMONEY"]       = TokenKind.KwSmallmoney,
        ["CHAR"]             = TokenKind.KwChar,
        ["CHARACTER"]        = TokenKind.KwChar,
        ["VARCHAR"]          = TokenKind.KwVarchar,
        ["NCHAR"]            = TokenKind.KwNchar,
        ["NVARCHAR"]         = TokenKind.KwNvarchar,
        ["TEXT"]             = TokenKind.KwText,
        ["NTEXT"]            = TokenKind.KwNtext,
        ["BINARY"]           = TokenKind.KwBinary,
        ["VARBINARY"]        = TokenKind.KwVarbinary,
        ["IMAGE"]            = TokenKind.KwImage,
        ["DATETIME"]         = TokenKind.KwDatetime,
        ["DATETIME2"]        = TokenKind.KwDatetime2,
        ["DATE"]             = TokenKind.KwDate,
        ["TIME"]             = TokenKind.KwTime2,
        ["DATETIMEOFFSET"]   = TokenKind.KwDatetimeoffset,
        ["SMALLDATETIME"]    = TokenKind.KwSmalldatetime,
        ["UNIQUEIDENTIFIER"] = TokenKind.KwUniqueidentifier,
        ["XML"]              = TokenKind.KwXml,
        ["SQL_VARIANT"]      = TokenKind.KwSql_Variant,
        ["ROWVERSION"]       = TokenKind.KwRowversion,
        ["TIMESTAMP"]        = TokenKind.KwTimestamp,
        ["HIERARCHYID"]      = TokenKind.KwHierarchyid,
        ["GEOGRAPHY"]        = TokenKind.KwGeography,
        ["GEOMETRY"]         = TokenKind.KwGeometry,

        // Misc
        ["USE"]               = TokenKind.KwUse,
        ["EXEC"]              = TokenKind.KwExec,
        ["EXECUTE"]           = TokenKind.KwExecute,
        ["OUTPUT"]            = TokenKind.KwOutput,
        ["OUT"]               = TokenKind.KwOut,
        ["DEFAULT"]           = TokenKind.KwDefault,
        ["IDENTITY"]          = TokenKind.KwIdentity,
        ["PRIMARY"]           = TokenKind.KwPrimary,
        ["FOREIGN"]           = TokenKind.KwForeign,
        ["KEY"]               = TokenKind.KwKey,
        ["CONSTRAINT"]        = TokenKind.KwConstraint,
        ["UNIQUE"]            = TokenKind.KwUnique,
        ["CHECK"]             = TokenKind.KwCheck,
        ["REFERENCES"]        = TokenKind.KwReferences,
        ["COLUMN"]            = TokenKind.KwColumn,
        ["ADD"]               = TokenKind.KwAdd,
        ["FOR"]               = TokenKind.KwFor,
        ["NOCOUNT"]           = TokenKind.KwNocount,
        ["ANSI_NULLS"]        = TokenKind.KwAnsi_nulls,
        ["ANSI_PADDING"]      = TokenKind.KwAnsi_padding,
        ["ANSI_WARNINGS"]     = TokenKind.KwAnsi_warnings,
        ["QUOTED_IDENTIFIER"] = TokenKind.KwQuoted_identifier,
        ["CONCAT_NULL_YIELDS_NULL"] = TokenKind.KwConcatNullYieldsNull,
        ["ARITH_ABORT"]       = TokenKind.KwArith_abort,
        ["XACT_ABORT"]        = TokenKind.KwXact_abort,
        ["ROWCOUNT"]          = TokenKind.KwRowcount,
        ["DATEFORMAT"]        = TokenKind.KwDateformat,
        ["LANGUAGE"]          = TokenKind.KwLanguage,
        ["OF"]                = TokenKind.KwOf,
        ["AT"]                = TokenKind.KwAt2,
        ["ZONE"]              = TokenKind.KwZone,
        ["OVER"]              = TokenKind.KwOver,
        ["PARTITION"]         = TokenKind.KwPartition,
        ["ROWS"]              = TokenKind.KwRows,
        ["RANGE"]             = TokenKind.KwRange,
        ["PRECEDING"]         = TokenKind.KwPreceding,
        ["FOLLOWING"]         = TokenKind.KwFollowing,
        ["CURRENT"]           = TokenKind.KwCurrent,
        ["ROW"]               = TokenKind.KwRow,
        ["UNBOUNDED"]         = TokenKind.KwUnbounded,
        ["PIVOT"]             = TokenKind.KwPivot,
        ["UNPIVOT"]           = TokenKind.KwUnpivot,
        ["TABLESAMPLE"]       = TokenKind.KwTablesample,
        ["SYSTEM"]            = TokenKind.KwSystem,
        ["READONLY"]          = TokenKind.KwReadonly,
        ["VARYING"]           = TokenKind.KwVarying,
        ["RECOMPILE"]         = TokenKind.KwRecompile,
        ["ENCRYPTION"]        = TokenKind.KwEncryption,
        ["SCHEMABINDING"]     = TokenKind.KwSchemabinding,
        ["MERGE"]             = TokenKind.KwMerge,
        ["MATCHED"]           = TokenKind.KwMatched,
        ["TARGET"]            = TokenKind.KwTarget,
        ["SOURCE"]            = TokenKind.KwSource,
        ["USING"]             = TokenKind.KwUsing,
        ["BULK"]              = TokenKind.KwBulk,
        ["OPENQUERY"]         = TokenKind.KwOpenquery,
        ["OPENDATASOURCE"]    = TokenKind.KwOpendatasource,
        ["OPENROWSET"]        = TokenKind.KwOpenrowset,
        ["OPENXML"]           = TokenKind.KwOpenxml,
        ["CONTAINS"]          = TokenKind.KwContains,
        ["FREETEXT"]          = TokenKind.KwFreetext,
        ["NATIVE_COMPILATION"]= TokenKind.KwNative_compilation,
    };
}
