using Microsoft.Extensions.Logging.Abstractions;
using SchemaConversion.Core.Models;
using SchemaConversion.Core.Options;
using Xunit;

namespace SchemaConversion.RuleEngine.Tests;

public class TableConverterTests
{
    private readonly TableConverter _converter;
    private readonly ConversionContext _context;

    public TableConverterTests()
    {
        var configDir = FindConfigDirectory();
        var typeMapper = new TypeMapper(
            Path.Combine(configDir, "type-mappings.json"),
            NullLogger<TypeMapper>.Instance);
        var functionMapper = new FunctionMapper(
            Path.Combine(configDir, "function-mappings.json"),
            NullLogger<FunctionMapper>.Instance);
        var expressionTranslator = new ExpressionTranslator(
            typeMapper, functionMapper, NullLogger<ExpressionTranslator>.Instance);

        _converter = new TableConverter(
            typeMapper, expressionTranslator, NullLogger<TableConverter>.Instance);

        _context = new ConversionContext
        {
            SessionId = "test-session",
            SchemaMappings = new Dictionary<string, string>
            {
                { "dbo", "public" },
                { "sales", "sales" }
            }
        };
    }

    [Fact]
    public void Convert_SimpleTable_ProducesCorrectDdl()
    {
        var obj = CreateSchemaObject("Customers", "dbo", @"
            CREATE TABLE dbo.Customers (
                CustomerID INT NOT NULL,
                FirstName NVARCHAR(100) NOT NULL,
                LastName NVARCHAR(100) NOT NULL,
                Email VARCHAR(255) NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.Equal(ConversionMethod.RuleBased, result.Method);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("CREATE TABLE public.customers", result.GeneratedDdl);
        Assert.Contains("customerid INTEGER NOT NULL", result.GeneratedDdl, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("firstname VARCHAR(100) NOT NULL", result.GeneratedDdl, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("email VARCHAR(255) NULL", result.GeneratedDdl, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Convert_TableWithIdentity_ConvertsToGeneratedAsIdentity()
    {
        var obj = CreateSchemaObject("Orders", "dbo", @"
            CREATE TABLE dbo.Orders (
                OrderID INT IDENTITY(1, 1) NOT NULL,
                OrderDate DATETIME NOT NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", result.GeneratedDdl);
    }

    [Fact]
    public void Convert_TableWithIdentitySeedAndIncrement_PreservesValues()
    {
        var obj = CreateSchemaObject("Sequences", "dbo", @"
            CREATE TABLE dbo.Sequences (
                SeqID INT IDENTITY(100, 5) NOT NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY (START WITH 100 INCREMENT BY 5)", result.GeneratedDdl);
    }

    [Fact]
    public void Convert_TableWithTinyint_AddsCheckConstraint()
    {
        var obj = CreateSchemaObject("Products", "dbo", @"
            CREATE TABLE dbo.Products (
                ProductID INT NOT NULL,
                Priority TINYINT NOT NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("SMALLINT", result.GeneratedDdl);
        Assert.Contains("CHECK", result.GeneratedDdl);
        Assert.Contains(">= 0", result.GeneratedDdl);
        Assert.Contains("<= 255", result.GeneratedDdl);
    }

    [Fact]
    public void Convert_TableWithDefaultGetdate_TranslatesDefault()
    {
        var obj = CreateSchemaObject("Audit", "dbo", @"
            CREATE TABLE dbo.Audit (
                AuditID INT NOT NULL,
                CreatedAt DATETIME DEFAULT GETDATE()
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("DEFAULT CURRENT_TIMESTAMP", result.GeneratedDdl);
    }

    [Fact]
    public void Convert_TableWithDefaultNewid_TranslatesDefault()
    {
        var obj = CreateSchemaObject("Records", "dbo", @"
            CREATE TABLE dbo.Records (
                RecordID UNIQUEIDENTIFIER DEFAULT NEWID(),
                Name NVARCHAR(50) NOT NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("DEFAULT gen_random_uuid()", result.GeneratedDdl);
    }

    [Fact]
    public void Convert_TableWithSchemaMapping_AppliesMapping()
    {
        var obj = CreateSchemaObject("OrderItems", "sales", @"
            CREATE TABLE sales.OrderItems (
                ItemID INT NOT NULL,
                Quantity INT NOT NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("CREATE TABLE sales.orderitems", result.GeneratedDdl);
    }

    [Fact]
    public void Convert_TableWithInlinePrimaryKey_IncludesPkConstraint()
    {
        var obj = CreateSchemaObject("Items", "dbo", @"
            CREATE TABLE dbo.Items (
                ItemID INT NOT NULL,
                Name NVARCHAR(100) NOT NULL,
                CONSTRAINT PK_Items PRIMARY KEY (ItemID)
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("PRIMARY KEY", result.GeneratedDdl);
        Assert.Contains("pk_items", result.GeneratedDdl.ToLowerInvariant());
    }

    [Fact]
    public void Convert_InvalidSql_ReturnsFailedStatus()
    {
        var obj = CreateSchemaObject("Bad", "dbo", "NOT VALID SQL AT ALL");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Failed, result.Status);
        Assert.NotNull(result.ErrorMessage);
    }

    [Fact]
    public void Convert_TableWithMoneyType_MapsToNumeric()
    {
        var obj = CreateSchemaObject("Prices", "dbo", @"
            CREATE TABLE dbo.Prices (
                PriceID INT NOT NULL,
                Amount MONEY NOT NULL
            );");

        var result = _converter.Convert(obj, _context);

        Assert.Equal(ConversionStatus.Converted, result.Status);
        Assert.NotNull(result.GeneratedDdl);
        Assert.Contains("NUMERIC(19,4)", result.GeneratedDdl);
    }

    private static SchemaObject CreateSchemaObject(string name, string schema, string ddl)
    {
        return new SchemaObject
        {
            Name = name,
            SchemaName = schema,
            ObjectType = SchemaObjectType.Table,
            SourceDefinition = ddl,
            SourceDefinitionHash = Convert.ToBase64String(
                System.Security.Cryptography.SHA256.HashData(
                    System.Text.Encoding.UTF8.GetBytes(ddl)))
        };
    }

    private static string FindConfigDirectory()
    {
        var dir = Directory.GetCurrentDirectory();
        while (dir is not null)
        {
            var configPath = Path.Combine(dir, "config");
            if (Directory.Exists(configPath) && File.Exists(Path.Combine(configPath, "type-mappings.json")))
            {
                return configPath;
            }
            dir = Directory.GetParent(dir)?.FullName;
        }

        throw new InvalidOperationException(
            "Could not find config directory. Ensure type-mappings.json and function-mappings.json exist in a config/ folder.");
    }
}
