using Microsoft.Extensions.Logging;
using Microsoft.SqlServer.TransactSql.ScriptDom;
using SchemaConversion.Core.Interfaces;
using SchemaConversion.Core.Models;
using SchemaConversion.Core.Options;
using SchemaConversion.RuleEngine.Models;

namespace SchemaConversion.RuleEngine;

/// <summary>
/// Converts SQL Server CREATE TABLE statements to PostgreSQL equivalents.
/// Handles column type mapping, IDENTITY → GENERATED BY DEFAULT AS IDENTITY,
/// DEFAULT expressions, computed columns, TINYINT CHECK constraints, and schema mapping.
/// </summary>
public sealed class TableConverter : IRuleBasedConverter
{
    private readonly TypeMapper _typeMapper;
    private readonly ExpressionTranslator _expressionTranslator;
    private readonly ILogger<TableConverter> _logger;

    public TableConverter(
        TypeMapper typeMapper,
        ExpressionTranslator expressionTranslator,
        ILogger<TableConverter> logger)
    {
        _typeMapper = typeMapper;
        _expressionTranslator = expressionTranslator;
        _logger = logger;
    }

    public ConversionResult Convert(SchemaObject obj, ConversionContext context)
    {
        _logger.LogDebug("Converting table {Schema}.{Name}", obj.SchemaName, obj.Name);

        var parser = new TSql160Parser(initialQuotedIdentifiers: false);
        using var reader = new StringReader(obj.SourceDefinition);
        var fragment = parser.Parse(reader, out var parseErrors);

        if (parseErrors.Count > 0)
        {
            var errorMessages = string.Join("; ", parseErrors.Select(e => e.Message));
            _logger.LogWarning("Parse errors for table {Name}: {Errors}", obj.Name, errorMessages);
            return new ConversionResult
            {
                ObjectName = obj.Name,
                SchemaName = obj.SchemaName,
                ObjectType = SchemaObjectType.Table,
                Status = ConversionStatus.Failed,
                Method = ConversionMethod.RuleBased,
                ErrorMessage = $"T-SQL parse errors: {errorMessages}"
            };
        }

        var createTableVisitor = new CreateTableVisitor();
        fragment.Accept(createTableVisitor);

        if (createTableVisitor.Table is null)
        {
            return new ConversionResult
            {
                ObjectName = obj.Name,
                SchemaName = obj.SchemaName,
                ObjectType = SchemaObjectType.Table,
                Status = ConversionStatus.Failed,
                Method = ConversionMethod.RuleBased,
                ErrorMessage = "No CREATE TABLE statement found in source definition."
            };
        }

        return ConvertTable(createTableVisitor.Table, obj, context);
    }

    private ConversionResult ConvertTable(CreateTableStatement createTable, SchemaObject obj, ConversionContext context)
    {
        var reviewFlags = new List<ManualReviewFlag>();
        var compatibilityNotes = new List<CompatibilityNote>();
        var needsAiFallback = false;

        var targetSchema = MapSchema(obj.SchemaName, context.SchemaMappings);
        var tableName = obj.Name;

        var columnDefs = new List<string>();
        var additionalConstraints = new List<string>();

        if (createTable.Definition?.ColumnDefinitions is not null)
        {
            foreach (var column in createTable.Definition.ColumnDefinitions)
            {
                var columnResult = ConvertColumn(column, tableName, context, reviewFlags, compatibilityNotes);
                if (columnResult.NeedsAiFallback)
                {
                    needsAiFallback = true;
                }
                columnDefs.Add(columnResult.ColumnDdl);

                if (columnResult.AdditionalConstraints.Count > 0)
                {
                    additionalConstraints.AddRange(columnResult.AdditionalConstraints);
                }
            }
        }

        // Handle inline table constraints (PK, FK, UNIQUE, CHECK defined inside CREATE TABLE)
        if (createTable.Definition?.TableConstraints is not null)
        {
            foreach (var constraint in createTable.Definition.TableConstraints)
            {
                var constraintDdl = ConvertInlineConstraint(constraint, context, reviewFlags, compatibilityNotes, ref needsAiFallback);
                if (constraintDdl is not null)
                {
                    additionalConstraints.Add(constraintDdl);
                }
            }
        }

        var allItems = new List<string>();
        allItems.AddRange(columnDefs);
        allItems.AddRange(additionalConstraints);

        var ddl = $"CREATE TABLE {targetSchema}.{QuoteIdentifier(tableName)} (\n" +
                  $"    {string.Join(",\n    ", allItems)}\n" +
                  $");";

        var status = needsAiFallback ? ConversionStatus.Flagged : ConversionStatus.Converted;

        return new ConversionResult
        {
            ObjectName = obj.Name,
            SchemaName = obj.SchemaName,
            ObjectType = SchemaObjectType.Table,
            Status = status,
            Method = ConversionMethod.RuleBased,
            GeneratedDdl = ddl,
            ConfidenceScore = needsAiFallback ? 0.6 : 1.0,
            ReviewFlags = reviewFlags,
            CompatibilityNotes = compatibilityNotes
        };
    }

    private ColumnConversionResult ConvertColumn(
        ColumnDefinition column,
        string tableName,
        ConversionContext context,
        List<ManualReviewFlag> reviewFlags,
        List<CompatibilityNote> compatibilityNotes)
    {
        var columnName = column.ColumnIdentifier?.Value ?? "unknown";
        var needsAiFallback = false;
        var additionalConstraints = new List<string>();

        // Map the data type
        var typeResult = MapColumnType(column, columnName);
        var pgType = typeResult.MappedType ?? "TEXT";

        if (typeResult.RequiresManualReview)
        {
            reviewFlags.Add(new ManualReviewFlag
            {
                Reason = $"Column '{columnName}': {typeResult.CompatibilityNote ?? "Type requires manual review"}",
                CodeSection = columnName,
                SuggestedAlternative = typeResult.MappedType
            });
            needsAiFallback = true;
        }

        // Handle TINYINT CHECK constraint
        if (typeResult.AdditionalConstraint is not null)
        {
            var checkConstraint = typeResult.AdditionalConstraint
                .Replace("{column}", QuoteIdentifier(columnName));
            additionalConstraints.Add(
                $"CONSTRAINT chk_{tableName}_{columnName}_range {checkConstraint}");
        }

        // Handle IDENTITY
        var identityClause = string.Empty;
        if (column.IdentityOptions is not null)
        {
            identityClause = ConvertIdentity(column.IdentityOptions);
        }

        // Handle computed columns
        if (column.ComputedColumnExpression is not null)
        {
            return ConvertComputedColumn(column, columnName, reviewFlags, ref needsAiFallback);
        }

        // Build column definition
        var parts = new List<string> { QuoteIdentifier(columnName), pgType };

        if (!string.IsNullOrEmpty(identityClause))
        {
            parts.Add(identityClause);
        }

        // Nullability
        if (column.Constraints is not null)
        {
            foreach (var constraint in column.Constraints)
            {
                if (constraint is NullableConstraintDefinition nullable)
                {
                    parts.Add(nullable.Nullable ? "NULL" : "NOT NULL");
                }
            }
        }

        // DEFAULT expression
        if (column.DefaultConstraint is not null)
        {
            var defaultResult = ConvertDefault(column.DefaultConstraint, context);
            if (defaultResult.NeedsAiFallback)
            {
                needsAiFallback = true;
                reviewFlags.Add(new ManualReviewFlag
                {
                    Reason = $"Column '{columnName}': DEFAULT expression could not be translated deterministically",
                    CodeSection = column.DefaultConstraint.Expression?.ToString() ?? "DEFAULT",
                    SuggestedAlternative = "AI-assisted translation recommended"
                });
            }
            else
            {
                parts.Add($"DEFAULT {defaultResult.Expression}");
            }
        }

        return new ColumnConversionResult
        {
            ColumnDdl = string.Join(" ", parts),
            NeedsAiFallback = needsAiFallback,
            AdditionalConstraints = additionalConstraints
        };
    }

    private ColumnConversionResult ConvertComputedColumn(
        ColumnDefinition column,
        string columnName,
        List<ManualReviewFlag> reviewFlags,
        ref bool needsAiFallback)
    {
        var sourceExpr = GetFragmentText(column.ComputedColumnExpression);
        var translationResult = _expressionTranslator.Translate(sourceExpr);

        if (translationResult.IsSuccess)
        {
            var ddl = $"{QuoteIdentifier(columnName)} {InferComputedColumnType()} GENERATED ALWAYS AS ({translationResult.TranslatedExpression}) STORED";
            return new ColumnConversionResult
            {
                ColumnDdl = ddl,
                NeedsAiFallback = false,
                AdditionalConstraints = []
            };
        }

        // Cannot translate — mark for manual review
        needsAiFallback = true;
        reviewFlags.Add(new ManualReviewFlag
        {
            Reason = $"Computed column '{columnName}' expression cannot be translated: {translationResult.CannotTranslateReason}",
            CodeSection = sourceExpr,
            SuggestedAlternative = "Consider AI-assisted translation or manual rewrite"
        });

        // Still emit the column with a comment
        var fallbackDdl = $"{QuoteIdentifier(columnName)} TEXT /* COMPUTED: {sourceExpr} — requires manual review */";
        return new ColumnConversionResult
        {
            ColumnDdl = fallbackDdl,
            NeedsAiFallback = true,
            AdditionalConstraints = []
        };
    }

    private TypeMappingResult MapColumnType(ColumnDefinition column, string columnName)
    {
        if (column.DataType is null)
        {
            return new TypeMappingResult
            {
                MappedType = null,
                RequiresManualReview = true,
                CompatibilityNote = $"Column '{columnName}' has no data type specified."
            };
        }

        var typeName = GetDataTypeName(column.DataType);
        int? precision = null;
        int? scale = null;
        int? length = null;

        if (column.DataType is SqlDataTypeReference sqlType)
        {
            var parameters = sqlType.Parameters;
            if (parameters.Count >= 1)
            {
                var firstParam = parameters[0].Value;
                if (firstParam.Equals("MAX", StringComparison.OrdinalIgnoreCase))
                {
                    length = -1;
                }
                else if (int.TryParse(firstParam, out var p))
                {
                    var upperType = typeName.ToUpperInvariant();
                    if (upperType.Contains("CHAR") || upperType.Contains("BINARY"))
                    {
                        length = p;
                    }
                    else
                    {
                        precision = p;
                    }
                }
            }
            if (parameters.Count >= 2 && int.TryParse(parameters[1].Value, out var s))
            {
                scale = s;
            }
        }

        return _typeMapper.MapType(typeName, precision, scale, length);
    }

    private static string GetDataTypeName(DataTypeReference dataType)
    {
        if (dataType is SqlDataTypeReference sqlType)
        {
            return sqlType.SqlDataTypeOption.ToString().ToUpperInvariant() switch
            {
                "NONE" => sqlType.Name?.BaseIdentifier?.Value ?? "UNKNOWN",
                var opt => opt
            };
        }

        return dataType.Name?.BaseIdentifier?.Value ?? "UNKNOWN";
    }

    private static string ConvertIdentity(IdentityOptions identity)
    {
        var seed = 1;
        var increment = 1;

        if (identity.IdentitySeed is IntegerLiteral seedLit)
        {
            int.TryParse(seedLit.Value, out seed);
        }

        if (identity.IdentityIncrement is IntegerLiteral incLit)
        {
            int.TryParse(incLit.Value, out increment);
        }

        if (seed == 1 && increment == 1)
        {
            return "GENERATED BY DEFAULT AS IDENTITY";
        }

        return $"GENERATED BY DEFAULT AS IDENTITY (START WITH {seed} INCREMENT BY {increment})";
    }

    private DefaultConversionResult ConvertDefault(DefaultConstraintDefinition defaultConstraint, ConversionContext context)
    {
        var sourceExpr = GetFragmentText(defaultConstraint.Expression);
        if (string.IsNullOrWhiteSpace(sourceExpr))
        {
            return new DefaultConversionResult { Expression = "NULL", NeedsAiFallback = false };
        }

        var result = _expressionTranslator.Translate(sourceExpr);
        if (result.IsSuccess)
        {
            return new DefaultConversionResult
            {
                Expression = result.TranslatedExpression!,
                NeedsAiFallback = false
            };
        }

        _logger.LogDebug("DEFAULT expression needs AI fallback: {Expr} — {Reason}",
            sourceExpr, result.CannotTranslateReason);

        return new DefaultConversionResult
        {
            Expression = sourceExpr,
            NeedsAiFallback = true
        };
    }

    private string? ConvertInlineConstraint(
        ConstraintDefinition constraint,
        ConversionContext context,
        List<ManualReviewFlag> reviewFlags,
        List<CompatibilityNote> compatibilityNotes,
        ref bool needsAiFallback)
    {
        return constraint switch
        {
            UniqueConstraintDefinition unique => ConvertInlineUniqueOrPk(unique),
            ForeignKeyConstraintDefinition fk => ConvertInlineForeignKey(fk, context),
            CheckConstraintDefinition check => ConvertInlineCheck(check, reviewFlags, ref needsAiFallback),
            _ => null
        };
    }

    private static string ConvertInlineUniqueOrPk(UniqueConstraintDefinition unique)
    {
        var constraintName = unique.ConstraintIdentifier?.Value;
        var columns = unique.Columns
            .Select(c => $"{QuoteIdentifier(c.Column?.MultiPartIdentifier?.Identifiers.Last().Value ?? "unknown")}{(c.SortOrder == SortOrder.Descending ? " DESC" : "")}")
            .ToList();

        var type = unique.IsPrimaryKey ? "PRIMARY KEY" : "UNIQUE";
        var nameClause = constraintName is not null
            ? $"CONSTRAINT {QuoteIdentifier(constraintName)} "
            : "";

        return $"{nameClause}{type} ({string.Join(", ", columns)})";
    }

    private string ConvertInlineForeignKey(ForeignKeyConstraintDefinition fk, ConversionContext context)
    {
        var constraintName = fk.ConstraintIdentifier?.Value;
        var nameClause = constraintName is not null
            ? $"CONSTRAINT {QuoteIdentifier(constraintName)} "
            : "";

        var columns = fk.Columns
            .Select(c => QuoteIdentifier(c.Value))
            .ToList();

        var refSchema = fk.ReferenceTableName?.SchemaIdentifier?.Value ?? "dbo";
        var refTable = fk.ReferenceTableName?.BaseIdentifier?.Value ?? "unknown";
        var mappedRefSchema = MapSchema(refSchema, context.SchemaMappings);

        var refColumns = fk.ReferencedTableColumns
            .Select(c => QuoteIdentifier(c.Value))
            .ToList();

        var onDelete = MapReferentialAction(fk.DeleteAction);
        var onUpdate = MapReferentialAction(fk.UpdateAction);

        return $"{nameClause}FOREIGN KEY ({string.Join(", ", columns)}) " +
               $"REFERENCES {mappedRefSchema}.{QuoteIdentifier(refTable)} ({string.Join(", ", refColumns)}) " +
               $"ON DELETE {onDelete} ON UPDATE {onUpdate}";
    }

    private string? ConvertInlineCheck(
        CheckConstraintDefinition check,
        List<ManualReviewFlag> reviewFlags,
        ref bool needsAiFallback)
    {
        var constraintName = check.ConstraintIdentifier?.Value;
        var nameClause = constraintName is not null
            ? $"CONSTRAINT {QuoteIdentifier(constraintName)} "
            : "";

        var sourceExpr = GetFragmentText(check.CheckCondition);
        var result = _expressionTranslator.Translate(sourceExpr);

        if (result.IsSuccess)
        {
            return $"{nameClause}CHECK ({result.TranslatedExpression})";
        }

        needsAiFallback = true;
        reviewFlags.Add(new ManualReviewFlag
        {
            Reason = $"CHECK constraint expression cannot be translated: {result.CannotTranslateReason}",
            CodeSection = sourceExpr,
            SuggestedAlternative = "AI-assisted translation recommended"
        });

        return $"{nameClause}CHECK ({sourceExpr}) /* requires review */";
    }

    private static string MapReferentialAction(DeleteUpdateAction action)
    {
        return action switch
        {
            DeleteUpdateAction.Cascade => "CASCADE",
            DeleteUpdateAction.SetNull => "SET NULL",
            DeleteUpdateAction.SetDefault => "SET DEFAULT",
            DeleteUpdateAction.NoAction => "NO ACTION",
            _ => "NO ACTION"
        };
    }

    private static string MapSchema(string sourceSchema, IReadOnlyDictionary<string, string> schemaMappings)
    {
        if (schemaMappings.TryGetValue(sourceSchema, out var mapped))
        {
            return mapped;
        }

        // Default: dbo → public, others keep same name
        return sourceSchema.Equals("dbo", StringComparison.OrdinalIgnoreCase)
            ? "public"
            : sourceSchema;
    }

    private static string QuoteIdentifier(string identifier)
    {
        if (identifier.All(c => char.IsLetterOrDigit(c) || c == '_'))
        {
            return identifier.ToLowerInvariant();
        }
        return $"\"{identifier}\"";
    }

    private static string GetFragmentText(TSqlFragment? fragment)
    {
        if (fragment is null) return string.Empty;

        // Build text from tokens
        var tokens = new List<string>();
        for (var i = fragment.FirstTokenIndex; i <= fragment.LastTokenIndex; i++)
        {
            if (i >= 0 && fragment.ScriptTokenStream is not null && i < fragment.ScriptTokenStream.Count)
            {
                tokens.Add(fragment.ScriptTokenStream[i].Text);
            }
        }
        return string.Join("", tokens).Trim();
    }

    private static string InferComputedColumnType()
    {
        // PostgreSQL requires explicit type for generated columns;
        // we use an empty string and let the expression determine the type
        // In practice, the type would need to be specified — using a placeholder
        return string.Empty;
    }

    private sealed class CreateTableVisitor : TSqlFragmentVisitor
    {
        public CreateTableStatement? Table { get; private set; }

        public override void Visit(CreateTableStatement node)
        {
            Table ??= node;
        }
    }

    private sealed record ColumnConversionResult
    {
        public required string ColumnDdl { get; init; }
        public required bool NeedsAiFallback { get; init; }
        public required IReadOnlyList<string> AdditionalConstraints { get; init; }
    }

    private sealed record DefaultConversionResult
    {
        public required string Expression { get; init; }
        public required bool NeedsAiFallback { get; init; }
    }
}
